# If you want to listen on all subjects, just pass one element ["channel.>"], otherwise
# pass the list of subjects (e.g ["channel.<channel_id>", "channel.<channel_id>.sub.topic.x", ...]).
[subjects]
filter = ["channel.>"]
